### ISSUE TITLE
move test data out into separate library

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/pbcore#57]
We have discussed a medium-term goal of moving the test data in pbcore and pbbam into a unified "sample PacBio data" package.

Goals:
- Tiny files
- Represent a few realistic use cases, maybe some corner cases
- Data files locations accessible by Python and C++ API
- Data files locations accessible by command line tools, e.g.

``` sh
  $ pacbio-sample-file tiny-aligned-bam
```

**Comment by mpkocher** [comment]
Here's some thoughts on a potential model.  I believe it address the items you've outlined.

https://gist.github.com/mpkocher/79333f8e1f9059914b8bdcdee3f17cea

**Comment by natechols** [comment]
I agree that we should have a JSON file cataloging everything.  The rest looks reasonable to me as well.

**Comment by mpkocher** [comment]
@mdsmith and @pezmaster31 Any comments or feedback?

**Comment by mdsmith** [comment]
Sounds good to me, especially with API and CLI accessors. I support using json, but we may still get an expansion of non-standardized naming to convey characteristics that lend certain datasets to boundary case testing, e.g. 'lambda', 'lambda-two-movie', 'aligned-lambda-one-zmw', 'empty-bam', 'empty-aligned-bam', 'bam-missing-pbi', 'aligned-bam-missing-pbi', 'rs-cmph5', 'rs-bam', etc. We can either:

1. accept that as an inevitability, because it isn't too bad now 
2. have a separate "internal-test" file repo with these arbitrary combinations 
3. disallow boundary case test files entirely or within reason, and force users to develop their own or generate them at test-time or 
4. develop a set of characteristics and allow for more advanced indexing (something like the pbi recarray).

We'll probably go with option 1, as it is what we have already and seems to work, but it is something to think about.

**Comment by mpkocher** [comment]
Would adding a "description" field help address this issue?

**Comment by natechols** [comment]
Yes, we probably need that anyway.

**Comment by mpkocher** [comment]
In version 1, the general idea I was going for would be to group files by whatever metric or grouping that make sense for your application or usecase within a bundle JSON file. 

Such as grouping by size, or "bad files" using huge.json, and bad-alignmentsets.json. 

However, I am open to other approaches to group within a bundle.

**Comment by mpkocher** [comment]
Updated with description https://gist.github.com/mpkocher/79333f8e1f9059914b8bdcdee3f17cea
